server:
    port: 8080

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
        username: root
        password: root
    redis:
      host: localhost
      database: 0
      port: 6379
      password:
      jedis:
        pool:
          max-active: 8 #连接池最大链接数（使用负值表示没有限制）
          max-wait: -1ms # 连接池最大阻塞等待时间　(使用负值表示没有限制)
          max-idle: 8 # 链接池中的最大空闲链接
          min-idle: 0 # 连接池中的最小空闲链接
      timeout: 3000ms # 链接池

mybatis:
      mapper-locations:
          - classpath:dao/*.xml
          - classpath*:com/**/mapper/*.xml
      type-aliases-package: com.yuper.mallspringboot
      configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 输出mysql　语句'


redis:
  key:
    prefix:
      authCode: "portal:authCode"
    expire:
      authCode: 120  # 验证码的有效时间